requirejs.config({
    baseUrl: "../../app/",
    paths: {
        "jquery": "libs/bower/jquery/dist/jquery.min",
        "socketio": "libs/bower/socket.io-client/socket.io",
        "angular": "libs/bower/angular/angular.min",
        "ui-bootstrap": "libs/bower/angular-bootstrap/ui-bootstrap",
        "ui-bootstrap-tpls": "libs/bower/angular-bootstrap/ui-bootstrap-tpls",
        "angularAMD": "libs/bower/angularAMD/angularAMD.min",

        "jquery-ui-dialog": "libs/bower/jquery-ui/ui/minified/dialog.min",
        "button": "libs/bower/jquery-ui/ui/minified/button.min",
        "core": "libs/bower/jquery-ui/ui/minified/core.min",
        "mouse": "libs/bower/jquery-ui/ui/minified/mouse.min",
        "draggable": "libs/bower/jquery-ui/ui/minified/draggable.min",
        "widget": "libs/bower/jquery-ui/ui/minified/widget.min",
        "position": "libs/bower/jquery-ui/ui/minified/position.min",
        "resizable": "libs/bower/jquery-ui/ui/minified/resizable.min",

        "jquery.cookie": "libs/bower/jquery.cookie/jquery.cookie",
        "qtip": "libs/bower/qtip2/jquery.qtip",
        "tv4": "libs/bower/tv4/tv4",
        "angular-xeditable": "libs/bower/angular-xeditable/dist/js/xeditable.min",
        "cytoscape": "libs/bower/cytoscape/dist/cytoscape",
        "cytoscape.navigator": "libs/ext/cytoscape.navigator/cytoscape.js-navigator",

        "bms.common": "main/bms.common",
        "bms.func": "main/bms.func",
        "bms.socket": "main/bms.socket",
        "bms.config": "main/bms.config",
        "bms.visualization": "main/bms.visualization",
        "bms.editor": "editor/bms.editor",
        "prob.ui": "main/prob.ui",
        "prob.iframe": "main/prob.iframe",
        "prob.editor": "main/prob.editor",
        "prob.common": "main/prob.common",
        "prob.modal": "main/prob.modal",
        "prob.graph": "main/prob.graph",
        "prob.jquery": "main/prob.jquery",
        "prob.observers": "main/prob.observers",
        "prob.online": "main/prob.online",
        "prob.integrated": "main/prob.integrated",
        "prob.standalone": "main/prob.standalone",
        "prob.vis": "main/prob.vis",

        "jquery.contextMenu": "libs/ext/contextmenu/jquery.contextMenu",
        "jquery.jgraduate": "libs/ext/jgraduate/jquery.jgraduate.min",
        "jpicker": "libs/ext/jgraduate/jpicker.min",
        "jquery.svgicons": "libs/ext/jquery.svgicons",
        "jquery.bbq": "libs/ext/jquerybbq/jquery.bbq.min",
        "jquery.browser": "libs/bower/jquery.browser/dist/jquery.browser.min",
        "jquery.hotkeys": "libs/ext/js-hotkeys/jquery.hotkeys.min",
        "jquery.draginput": "libs/ext/jquery-draginput",
        "mousewheel": "libs/ext/mousewheel",
        "taphold": "libs/ext/taphold",
        "touch": "libs/ext/touch",
        "requestanimationframe": "libs/ext/requestanimationframe",
        "browser": "editor/src/browser",
        "contextmenu": "editor/src/contextmenu",
        "dialog": "editor/src/dialog",
        "draw": "editor/src/draw",
        "history": "editor/src/history",
        "math": "editor/src/math",
        "method-draw": "editor/src/method-draw",
        "path": "editor/src/path",
        "sanitize": "editor/src/sanitize",
        "select": "editor/src/select",
        "svgcanvas": "editor/src/svgcanvas",
        "svgtransformlist": "editor/src/svgtransformlist",
        "svgutils": "editor/src/svgutils",
        "units": "editor/src/units"
    },
    shim: {
        "prob.jquery": ['bms.func', 'jquery'],
        "socketio": {"exports": "io"},
        "jquery": {"exports": "$"},
        "angular": {"exports": "angular"},
        "angularAMD": ["angular"],
        "ui-bootstrap": ["angular"],
        "ui-bootstrap-tpls": ["ui-bootstrap"],
        "angular-xeditable": ["angular"],
        "qtip": ["jquery"],
        "cytoscape": {
            exports: "cy",
            deps: ["jquery"]
        },
        "cytoscape.navigator": ['cytoscape'],
        "jpicker": ["jquery.jgraduate"],
        "jquery.jgraduate": ["jquery"],
        "jquery.contextMenu": ["jquery"],
        "jquery.bbq": ["jquery", "jquery.browser"],
        "jquery.hotkeys": ["jquery"],
        "jquery.draginput": ["jquery"],
        "jquery.svgicons": ["jquery"],
        "taphold": ["jquery"],
        "mousewheel": ["jquery"],
        "contextmenu": ["jquery", "method-draw"],
        "sanitize": ["jquery"],
        "svgcanvas": ["jquery"],
        "units": ["jquery"],
        "dialog": ["jquery", "jquery-ui-dialog"],
        "svgutils": ["browser"],
        "method-draw": [
            "jquery", "jquery.bbq", "jquery.svgicons",
            "units", "math", "svgutils", "sanitize",
            "history", "select", "draw", "path", "dialog",
            "jquery.contextMenu", "svgcanvas", "browser"
        ]
    }
});