requirejs.config({
    baseUrl: "../../app/",
    paths: {
        "jquery": "libs/bower/jquery/dist/jquery.min",
        "angular": "libs/bower/angular/angular.min",
        "angular-route": "libs/bower/angular-route/angular-route.min",
        "ui-bootstrap": "libs/bower/angular-bootstrap/ui-bootstrap",
        "ui-bootstrap-tpls": "libs/bower/angular-bootstrap/ui-bootstrap-tpls",
        "angularAMD": "libs/bower/angularAMD/angularAMD.min",
        "socketio": "libs/bower/socket.io-client/socket.io",
        "bootstrap": "libs/bower/bootstrap/dist/js/bootstrap.min",
        "jquery.cookie": "libs/bower/jquery.cookie/jquery.cookie",
        "jquery-ui": "libs/bower/jquery-ui/jquery-ui.min",
        "xeditable": "libs/bower/angular-xeditable/dist/js/xeditable.min",
        "cytoscape": "libs/bower/cytoscape/dist/cytoscape",
        "cytoscape.navigator": "libs/ext/cytoscape.js-navigator",
        "bms.common": "src/bmotion/bms.common",
        "bms.func": "src/bmotion/bms.func",
        "prob.ui": "src/prob/prob.ui",
        "prob.iframe": "src/prob/prob.iframe",
        "prob.common": "src/prob/prob.common",
        "prob.modal": "src/prob/prob.modal",
        "prob.graph": "src/prob/prob.graph",
        "prob.jquery": "src/prob/prob.jquery",
        "prob.observers": "src/prob/prob.observers",
        "prob.online": "src/prob/prob.online",
        "prob.integrated": "src/prob/prob.integrated",
        "bmotion.config": "src/bmotion.config",
        "prob.standalone": "src/prob/prob.standalone",
        "prob.vis": "src/prob/prob.vis",
        "qtip": "libs/bower/qtip2/jquery.qtip",
        "tv4": "libs/bower/tv4/tv4"
    },
    shim: {
        "socketio": {"exports": "io"},
        "jquery": {"exports": "$"},
        "angular": {"exports": "angular"},
        "angularAMD": ["angular"],
        "angular-route": ["angular"],
        "ui-bootstrap": ["angular"],
        "ui-bootstrap-tpls": ["ui-bootstrap"],
        "jquery-ui": ["jquery"],
        "bootstrap": ["jquery"],
        "xeditable": ["angular"],
        "qtip": ["jquery"],
        "cytoscape": {
            exports: "cy",
            deps: ["jquery"]
        },
        "cytoscape.navigator": ['cytoscape']
    }
});